### ISSUE TITLE
Заменить svg-изображения МасКота на новые

### ISSUE THREAD

**Issue by fowesn** [week-password/wlss-frontend#105]
Сейчас у кота прозрачные глаза, нос и уши, необхоидмо заменить на аналогичные изображения, но с белым фоном
1. [макет МасКота](https://www.figma.com/file/vqX1rJ9odDeW6uV3GYH077/Wisher?type=design&node-id=82-53&mode=design&t=cazCsEr7zHCkSpMe-0)
2. [макет МасКота в коробке](https://www.figma.com/file/vqX1rJ9odDeW6uV3GYH077/Wisher?type=design&node-id=82-53&mode=design&t=cazCsEr7zHCkSpMe-0)

**Comment by birthdaysgift** [comment]
С белым фоном выглядит намного лучше! круто, что заметила и обновила <3
