### ISSUE TITLE
Настроить роутинг

### ISSUE THREAD

**Issue by fowesn** [week-password/wlss-frontend#24]
Необходимо настроить роутинг и добавить модули / компоненты для основных разделов:
- [x] профиль
- [x] авторизация
- [x] регистрация
- [x] юридические документы
- [x] 404

**Comment by fowesn** [comment]
Поскольку у меня вызывают невероятные трудности названия юридических документов, оставлю это тут:
1. Политика конфиденциальности = Privacy Policy
2. Согласие на обработку персональных данных = Пользовательское соглашение = Consent to Personal Data Processing = User Agreement 

На данный момент у нас есть только два этих документа ([#13](https://github.com/week-password/wisher/issues/13) и [#16](https://github.com/week-password/wisher/issues/16) в репозитории [Wisher](https://github.com/week-password/wisher)).
Политика конфиденциальности упоминается в cookie-баннере, также обсудили с @birthdaysgift, что политику конфиденциальности и согласие на обработку ПД нужно будет добавить на форму регистрации. 
В рамках этого тикета подготовила страницы `/terms/privacy-policy` и `/terms/user-agreement` под эти документы.

**Comment by birthdaysgift** [comment]
> Поскольку у меня вызывают невероятные трудности названия юридических документов, оставлю это тут:
> 1. Политика конфиденциальности = Privacy Policy
> 2. Согласие на обработку персональных данных = Пользовательское соглашение = Consent to Personal Data Processing = User Agreement 

Думаю эту инфу можно будет внести в вики по юридическим соглашениям, как только мы добавим туда все соглашения.
