### ISSUE TITLE
Рефакторинг стиля кодирования HTML

### ISSUE THREAD

**Issue by fowesn** [week-password/wlss-frontend#68]
Сейчас, если атрибуты HTML-элемента делают строку слишком длинной, то каждый атрибут, за исключением первого, переносится на новую строку с выравниванием по первому символу первого атрибута.

Несмотря на то, что этот подход во многих случаях делает HTML более читаемым, у него есть значительные недостатки:

1. Если у HTML-элемента всего один атрибут, его нельзя перенести на другую строку. Это становится проблемой (особенно на 4 и более уровнях вложенности), когда у тэга HTML-элемента длинное название, или значение атрибута очень длинное, или обе эти вещи вместе. Часто встречается длинное значение атрибута `class`.
``` html
<div class="some-class">
  <some-very-long-html-tag-name class="some-class__element some-class__element_modificator1 some-class__element_modificator2"
  ></some-very-long-html-tag-name>
</div>
```
2. Если у HTML-элемента 2 или больше атрибутов и имя тэга HTML элемента слишком длинное, становится сложно переносить каждый атрибут на нужное место.
``` html
<some-very-long-html-tag-name attribute1="value1"
                              attribute2="value2"
                              attribute3="value3"
></some-very-long-html-tag-name>
```
3. Если у HTML-элемента большое количество атрибутов и длина названия тэга 6+ символов, зрительно кажется, что на этом месте появился неправильно табулированный элемент.
``` html
<div>
  <h1>Some title</h1>
</div>
<div>
  <div>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <some-action-element class="some-class"
                         :class="{
                           'some-conditional-class': condition,
                         }"
                         attribute1="value2"
                         attribute2="value2"
                         attribute3="value3"
                         attribute4="value4"
                         attribute5="value5"
                         attribute6="value6"
    ></some-action-element>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
</div>
```
4. Если в дополнение к ситуации, описанной в п.3, в вёрстке появляется второй HTML-элемент с отличным названием тэга и большим количеством атрибутов, зрительно кажется, что в HTML-документе вообще нет никакого порядка и для всех элементов используется случайным образом выбранный размер табуляции. Ощущение беспорядка тем больше, чем больше таких HTML-элементов в вёрстке одного документа.
``` html
<div>
  <h1>Some title</h1>
</div>
<div>
  <div>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
    <some-action-element class="some-class"
                         :class="{
                           'some-conditional-class': condition,
                         }"
                         attribute1="value2"
                         attribute2="value2"
                         attribute3="value3"
                         attribute4="value4"
                         attribute5="value5"
                         attribute6="value6"
    ></some-action-element>
    <some-another-action-element class="some-class"
                                 :class="{
                                   'some-conditional-class': condition,
                                   'some-another-conditional-class': anotherCondition,
                                 }"
                                 attribute1="value1"
                                 attribute2="value2"
                                 attribute3="value3"
    ></some-another-action-element>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
    <short-tag class="some-class"
               :class="{
                 'some-conditional-class': condition,
               }"
               attribute1="value1"
               attribute2="value2"
               attribute3="value3"
               attribute4="value4"
    ></short-tag>
  </div>
</div>
```
5. Когда у HTML-элемента переносятся атрибуты по вышеописанному правилу, это усложняет изменение их порядка - первый элемент нельзя поменять местами с каким-либо другим, используя горячие клавиши для того, чтобы менять строки местами.

В реальности ситуация выглядит ещё хуже, чем в вышеописанных примерах, поскольку у атрибутов HTML-элементов разная длина и у их значений разная длина.  

В рамках задачи, необходимо провести рефакторинг HTML-файлов, заменив вышеописанное правило выставления отступов атрибутов на правило, согласно которому:
1. Каждый атрибут может быть перенесён на новую строку, если это необходимо, даже если у HTML-элемента всего один атрибут.
2. Если требуется перенос атрибутов HTML-элемента на новую строку, каждый атрибут должен быть перенесён на новую строку, в том числе первый.
3. При переносе атрибута на новую строку размер отступа равняется одной табуляции от символа, открывающего тэг HTML-элемента `<`

PS: Максимально допустимая длина строки для HTML-файлов будет установлена позже вместе с HTML-линтерами.

**Comment by birthdaysgift** [comment]
Можно также глянуть [пост](https://stackoverflow.com/questions/44944936/indenting-html-tags-on-multiple-lines) на SO, где обсуждается та же проблема
