### ISSUE TITLE
Рефакторинг аннотации типов массивов

### ISSUE THREAD

**Issue by fowesn** [week-password/wlss-frontend#69]
В typescript аннотировать типы массивов можно несколькими способами. Сейчас проекте используются два из них:
1. `const arr: number[]`
2. `const arr: Array<number>`

Для консистентности необходимо по всему проекту заменить аннотацию типов массивов на `Array<type>`. Этот способ аннотации выбран, поскольку, когда используются составные типы (например, `IWish & IWishBooking`), массивы, аннотированные такими типами выглядят лучше при использовании `Array<type & anotherType>`, чем `(type & anotherType)[]`.

**Comment by birthdaysgift** [comment]
В `typescript-eslint` есть правило [array-type](https://typescript-eslint.io/rules/array-type/), которое можно включить, чтобы проверять такие моменты на соответствие тому или иному выбранному стилю.
